namespace backend.Dtos;

// Outgoing payload returned to the Angular frontend
public class ChatResponseDto
{
    // Natural language answer generated by Azure OpenAI
    public string Response { get; set; } = string.Empty;

    // Raw DB rows serialised as a list of objects (can be empty)
    public IEnumerable<object> Data { get; set; } = [];

    // The session GUID used for this conversation thread
    public string SessionId { get; set; } = string.Empty;

    // Resolved SQL (values inlined) for copy-paste debugging. Null when flag is off.
    public string? ExecutedQuery { get; set; }

    // The intent that was matched – lets the frontend choose the right visual component
    public string Intent { get; set; } = "LcStatus";

    // Visual layout hint:  "table" | "approval_list" | "metric_cards" | "bank_chart" | "timeline" | "text_only"
    public string ResponseType { get; set; } = "table";

    // Human-readable label for the response card header
    public string ResponseLabel { get; set; } = "Unknown";

    // Sub-chart hint for metric_cards: "doughnut" | "stacked_bar" | "count_grid" | null
    // For bank_chart: "horizontal_bar" | null
    public string? ChartType { get; set; }

    // True when the response was produced by AI-generated (Text-to-SQL) rather than a hardcoded query
    public bool IsTextToSql { get; set; }

    // AI-classified query type: "list"|"aggregate"|"single_stat"|"timeline"|"comparison"|"trend"|"correlation"|"risk"|"kpi"|"heatmap"
    public string? QueryType { get; set; }

    // AI-generated follow-up questions shown as chips below the response
    public string[] SuggestedQuestions { get; set; } = [];

    // Populated when the user's entity (bank/customer/LC number) was not found in the DB
    public ClarificationDto? Clarification { get; set; }
}
